### PR TITLE
Add Brazilian Credit Cards Support

### PR DESCRIPTION
**Pull request by williankeller**
### Description
Local Brazilian Credit Cards added in Magento_Payment module and available for usage in other Magento 2 modules which implement integration with Payment Gateways.

### Fixed Issues
1. magento/payment-improvements#1: Add Brazilian Credit Cards Support

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by vkublytskyi** [comment]
@williankeller Thank you for your contribution. We will process this PR shortly.

**Comment by vkublytskyi** [comment]
@williankeller For full implementation additional fixes should be applied:

1. Information about card types should be added to https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Payment/view/base/web/js/model/credit-card-validation/credit-card-number-validator/credit-card-type.js. Otherwise it will lead to incorrect behavior at https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Payment/view/base/web/js/model/credit-card-validation/credit-card-number-validator.js#L45
3. Optionally regexp for new cards should be added to https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Payment/Model/Method/Cc.php#L126 (this is deprecated code but if change does not require a lot of effort it's better to update this logic as well)

**Comment by williankeller** [comment]
Hi @vkublytskyi, I'm on it.
I will provide these fixes you requested in a feel hours.

**Comment by williankeller** [comment]
Hi @vkublytskyi, I just saw your last commits. What are the next steps to we proceed with this PR?

**Comment by vkublytskyi** [comment]
@williankeller Thank you that reminded about this valuable contribution. As CLA is signed I think we are good to go and merge this code into main Magento repository. As a next step, I will run full tests suite on internal infrastructure to ensure all tests are green.

Thank you for your contribution and patience.

**Pull request merged**
